version: "3"

services:
  postgres-local:
    image: postgres
    restart: unless-stopped
    container_name: load-server-postgres-local
    environment:
        POSTGRES_USER: psql_user
        POSTGRES_DB: postgres
        POSTGRES_PASSWORD: psql_pass
    ports:
      - "9432:5432"
    volumes:
      - ./artifacts/psql_data:/var/lib/postgresql/data

  load-test-server-go:
    image: load-test-server-go
    restart: unless-stopped
    container_name: load-test-server-go
    ports:
      - 9080:9080
    volumes:
      - ./artifacts/employees:/employees
      - ./artifacts/logs/err:/logs/err
    environment:
        DATABASE_HOST: postgres-local
        DATABASE_PORT: 5432
        DATABASE_USER: psql_user
        DATABASE_PASS: psql_pass
        DATABASE_DBNAME: postgres
        FLUSH_PERIOD_IN_SECONDS: 5
    depends_on:
      - postgres-local

  kafka-ui:
    container_name: load-test-kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 9091:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      DYNAMIC_CONFIG_ENABLED: "true"

  kafka:
    container_name: load-test-kafka
    image: confluentinc/cp-kafka:7.5.4.arm64
    ports:
      - 9092:9092
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:29093"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'

  kafka-init-topics:
    container_name: load-test-init-topics
    image: confluentinc/cp-kafka:7.5.4.arm64
    depends_on:
      - kafka
    command: "bash -c 'echo Waiting for Kafka to be ready... && \
        cub kafka-ready -b kafka:29092 1 30 && \
        kafka-topics --create --topic load-test-topic --partitions 2 --replication-factor 1 --if-not-exists --bootstrap-server kafka:29092'"

  mongo:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - 27017:27017
    volumes:
      - ./artifacts/mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass

  mongo-express:
    image: mongo-express
    container_name: load-test-mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_AUTH_USERNAME=root
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=pass
    depends_on:
      - mongo
    ports:
      - 8888:8081

  load-test-spark-writer:
    image: load-test-spark-writer
    container_name: load-test-spark-writer
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: fitness_topic
    volumes:
      - ./artifacts/employees:/employees
      - ./artifacts/logs/err:/logs/err
    depends_on:
      - kafka

  load-test-kafka-consumer:
    image: load-test-kafka-consumer
    restart: unless-stopped
    container_name: load-test-kafka-consumer
    environment:
      KAFKA_TOPIC: load-test-topic
      KAFKA_BOOTSTRAP: kafka:29092
      CONSUMER_GROUP_NAME: load-test-consumer-group
      MONGO_URI: mongodb://mongo:27017
      MONGO_DATABASE: load-test-mongo-db
      MONGO_COLLECTION: load-test-mongo-collection
      MONGO_USER: root
      MONGO_PASS: pass
    volumes:
      - ./artifacts/employees:/employees
      - ./artifacts/logs/err:/logs/err
    depends_on:
      - kafka
      - mongo